<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // Warriors' 2nd defensive slot ("shield" type, alongside their regular "armor" chest piece — see
            // the shield/plate item lines further below for the rest of both tiers ladders). Legendary chest
            // piece: lowered from a solo-slot 150 def to 65, since it's now one of two pieces rather than a
            // warrior's only defense item — see the shield ladder (still 150 at this tier) for the other half.
            ['key' => 'aegis_plate', 'name' => 'Aegis Plate', 'type' => 'armor', 'class_key' => 'warrior', 'min_level' => 35, 'rarity' => 'legendary', 'glyph' => '🛡', 'description' => 'Impenetrable plate armor blessed by the old gods — the chest half of a warrior\'s armor+shield set.', 'stat_json' => ['def' => 65], 'price_gold' => null, 'price_gems' => 1500],
            ['key' => 'health_potion', 'name' => 'Health Potion', 'type' => 'consumable', 'rarity' => 'common', 'glyph' => '🧪', 'description' => 'Restores 40% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 40], 'price_gold' => 50, 'price_gems' => null],
            ['key' => 'greater_health_potion', 'name' => 'Greater Health Potion', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🧪', 'description' => 'Restores 70% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 70], 'price_gold' => 180, 'price_gems' => null],
            ['key' => 'mana_potion', 'name' => 'Mana Potion', 'type' => 'consumable', 'rarity' => 'common', 'glyph' => '💧', 'description' => 'Restores 40% of your max MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 40], 'price_gold' => 50, 'price_gems' => null],
            ['key' => 'greater_mana_potion', 'name' => 'Greater Mana Potion', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '💧', 'description' => 'Restores 70% of your max MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 70], 'price_gold' => 180, 'price_gems' => null],
            ['key' => 'vitality_tonic', 'name' => 'Vitality Tonic', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🌿', 'description' => '+50% HP regen rate for 10 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 50, 'duration_seconds' => 600], 'price_gold' => 220, 'price_gems' => null],
            ['key' => 'focus_tonic', 'name' => 'Focus Tonic', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🔷', 'description' => '+50% mana regen rate for 10 minutes. Usable anytime, even outside battle.', 'stat_json' => ['mana_regen_pct_buff' => 50, 'duration_seconds' => 600], 'price_gold' => 220, 'price_gems' => null],
            ['key' => 'elixir_of_vigor', 'name' => 'Elixir of Vigor', 'type' => 'consumable', 'rarity' => 'epic', 'glyph' => '✨', 'description' => '+40% HP and mana regen rate for 15 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 40, 'mana_regen_pct_buff' => 40, 'duration_seconds' => 900], 'price_gold' => null, 'price_gems' => 500],
            ['key' => 'elixir_of_power', 'name' => 'Elixir of Power', 'type' => 'consumable', 'rarity' => 'legendary', 'glyph' => '⚗', 'description' => 'Grants +50% ATK for your next three fights.', 'stat_json' => ['atk_pct_buff' => 50, 'buff_fights' => 3], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'golden_crown', 'name' => 'Golden Crown', 'type' => 'cosmetic', 'rarity' => 'legendary', 'glyph' => '👑', 'description' => 'A pure flex — no combat stats, all prestige.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'stone', 'name' => 'Stone', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🪨', 'description' => 'Plain rock — all a fresh pickaxe turns up. Rank up Mining to start finding ore.', 'stat_json' => [], 'price_gold' => 5, 'price_gems' => null],
            ['key' => 'iron_ore', 'name' => 'Iron Ore', 'type' => 'material', 'rarity' => 'common', 'glyph' => '💎', 'description' => 'Basic mining material — unlocked at Mining level 8. Smelt it into bars before crafting.', 'stat_json' => [], 'price_gold' => 10, 'price_gems' => null],
            ['key' => 'silver_ore', 'name' => 'Silver Ore', 'type' => 'material', 'rarity' => 'epic', 'glyph' => '🔹', 'description' => 'A richer vein — unlocked at Mining level 20.', 'stat_json' => [], 'price_gold' => 30, 'price_gems' => null],
            ['key' => 'gold_ore', 'name' => 'Gold Ore', 'type' => 'material', 'rarity' => 'legendary', 'glyph' => '🟡', 'description' => 'A gleaming vein — unlocked at Mining level 35.', 'stat_json' => [], 'price_gold' => 120, 'price_gems' => null],
            ['key' => 'mythril_ore', 'name' => 'Mythril Ore', 'type' => 'material', 'rarity' => 'mythic', 'glyph' => '🔷', 'description' => 'A near-mythical vein — unlocked at Mining level 50.', 'stat_json' => [], 'price_gold' => 300, 'price_gems' => null],
            ['key' => 'wood', 'name' => 'Wood', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🪵', 'description' => 'Plain lumber — all a fresh axe turns up. Rank up Woodchopping to start finding rarer timber.', 'stat_json' => [], 'price_gold' => 8, 'price_gems' => null],
            ['key' => 'oak_wood', 'name' => 'Oak Wood', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🌳', 'description' => 'Sturdier timber — unlocked at Woodchopping level 8.', 'stat_json' => [], 'price_gold' => 18, 'price_gems' => null],
            ['key' => 'ironwood', 'name' => 'Ironwood', 'type' => 'material', 'rarity' => 'epic', 'glyph' => '🌲', 'description' => 'Dense, iron-hard timber — unlocked at Woodchopping level 20.', 'stat_json' => [], 'price_gold' => 28, 'price_gems' => null],
            ['key' => 'elderwood', 'name' => 'Elderwood', 'type' => 'material', 'rarity' => 'legendary', 'glyph' => '🍂', 'description' => 'Ancient, richly grained timber — unlocked at Woodchopping level 35.', 'stat_json' => [], 'price_gold' => 110, 'price_gems' => null],
            ['key' => 'moonwood', 'name' => 'Moonwood', 'type' => 'material', 'rarity' => 'mythic', 'glyph' => '🌙', 'description' => 'Pale, near-mythical timber — unlocked at Woodchopping level 50.', 'stat_json' => [], 'price_gold' => 280, 'price_gems' => null],
            ['key' => 'iron_bar', 'name' => 'Iron Bar', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🔩', 'description' => 'Iron ore smelted at the forge, ready for crafting.', 'stat_json' => [], 'price_gold' => 25, 'price_gems' => null],
            ['key' => 'silver_bar', 'name' => 'Silver Bar', 'type' => 'material', 'rarity' => 'epic', 'glyph' => '⬜', 'description' => 'Silver ore smelted at the forge — unlocked at Smelting level 15.', 'stat_json' => [], 'price_gold' => 65, 'price_gems' => null],
            ['key' => 'gold_bar', 'name' => 'Gold Bar', 'type' => 'material', 'rarity' => 'legendary', 'glyph' => '🥇', 'description' => 'Gold ore smelted at the forge — unlocked at Smelting level 30.', 'stat_json' => [], 'price_gold' => 200, 'price_gems' => null],
            ['key' => 'mythril_bar', 'name' => 'Mythril Bar', 'type' => 'material', 'rarity' => 'mythic', 'glyph' => '💠', 'description' => 'Mythril ore smelted at the forge — unlocked at Smelting level 45.', 'stat_json' => [], 'price_gold' => 480, 'price_gems' => null],
            // Every class crafts its OWN weapon+armor line at EVERY rarity tier — no more universal
            // "anyone can craft it" gear. Warrior's armor slot is explicitly a shield/aegis line (not
            // generic body armor) at every tier, so it reads unambiguously as "weapon + shield" in the UI.
            // Flavor stats: warrior = raw atk/def, rogue = atk+crit, ranger = atk/def+dodge, mage = atk/def+mp.

            // Rangers uniquely carry two simultaneously-equipped combat items — a bow (weapon slot, below)
            // and a quiver (its own 'quiver' slot) — mirroring the warrior's weapon+shield identity.
            // The quiver is flavored as flat "arrow damage" (atk) plus a bit of crit, distinct from the
            // bow's own dodge flavor, so equipping both is a real, felt stat gain rather than a formality.
            ['key' => 'worn_quiver', 'name' => 'Worn Quiver', 'type' => 'quiver', 'weapon_category' => 'quiver', 'class_key' => 'ranger', 'rarity' => 'common', 'min_level' => 1, 'glyph' => '🎯', 'description' => 'A handful of scavenged arrows in a battered leather quiver — every ranger starts with one.', 'stat_json' => ['atk' => 10], 'price_gold' => 700, 'price_gems' => null],

            // Common/Iron tier (level 8, needs Smelting rank) — weapon + shield/armor per class.
            ['key' => 'iron_sword', 'name' => 'Iron Sword', 'type' => 'weapon', 'weapon_category' => 'sword', 'class_key' => 'warrior', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '⚔', 'description' => 'A plain but reliable blade, forged for the front line.', 'stat_json' => ['atk' => 42], 'price_gold' => 2200, 'price_gems' => null],
            ['key' => 'iron_dagger', 'name' => 'Iron Dagger', 'type' => 'weapon', 'weapon_category' => 'dagger', 'class_key' => 'rogue', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '🗡', 'description' => 'A basic dagger, best forged fresh from raw materials — or bought outright, if the coin is there.', 'stat_json' => ['atk' => 40, 'crit' => 2], 'price_gold' => 2200, 'price_gems' => null],
            ['key' => 'wooden_bow', 'name' => 'Wooden Bow', 'type' => 'weapon', 'weapon_category' => 'bow', 'class_key' => 'ranger', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '🏹', 'description' => 'A simple bow carved from chopped wood.', 'stat_json' => ['atk' => 45], 'price_gold' => 2200, 'price_gems' => null],
            ['key' => 'fletchers_quiver', 'name' => "Fletcher's Quiver", 'type' => 'quiver', 'weapon_category' => 'quiver', 'class_key' => 'ranger', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '🎯', 'description' => 'Hand-fletched arrows that fly straighter and bite harder.', 'stat_json' => ['atk' => 22, 'crit' => 2], 'price_gold' => 1700, 'price_gems' => null],
            ['key' => 'oak_staff', 'name' => 'Oak Staff', 'type' => 'weapon', 'weapon_category' => 'staff', 'class_key' => 'mage', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '🔮', 'description' => 'A gnarled oak staff that channels a modest reserve of mana.', 'stat_json' => ['atk' => 30, 'mp' => 15], 'price_gold' => 2200, 'price_gems' => null],
            ['key' => 'iron_buckler', 'name' => 'Iron Buckler', 'type' => 'shield', 'class_key' => 'warrior', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '🛡', 'description' => "A round iron shield strapped to the forearm — a warrior's second, always-on defensive slot alongside their chest armor.", 'stat_json' => ['def' => 35], 'price_gold' => 2200, 'price_gems' => null],
            ['key' => 'plate_hauberk', 'name' => 'Plate Hauberk', 'type' => 'armor', 'class_key' => 'warrior', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '🥋', 'description' => 'A riveted plate hauberk — the chest half of a warrior\'s two-piece defense.', 'stat_json' => ['def' => 15], 'price_gold' => 2200, 'price_gems' => null],
            ['key' => 'leather_vest', 'name' => 'Leather Vest', 'type' => 'armor', 'class_key' => 'rogue', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '🥋', 'description' => 'Light, flexible armor that never slows a blade down.', 'stat_json' => ['def' => 22, 'crit' => 3], 'price_gold' => 2200, 'price_gems' => null],
            ['key' => 'ranger_cloak', 'name' => "Ranger's Cloak", 'type' => 'armor', 'class_key' => 'ranger', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '🧥', 'description' => 'A weathered cloak that helps you slip out of harm\'s way.', 'stat_json' => ['def' => 22, 'dodge_pct' => 8], 'price_gold' => 2200, 'price_gems' => null],
            ['key' => 'padded_robe', 'name' => 'Padded Robe', 'type' => 'armor', 'class_key' => 'mage', 'rarity' => 'common', 'min_level' => 8, 'glyph' => '👘', 'description' => 'A quilted robe woven to hold a bit of extra mana.', 'stat_json' => ['def' => 20, 'mp' => 20], 'price_gold' => 2200, 'price_gems' => null],

            // Rare tier (level 15) — the previously-missing rare weapon/armor rung, now filled for every class.
            ['key' => 'steel_broadsword', 'name' => 'Steel Broadsword', 'type' => 'weapon', 'weapon_category' => 'sword', 'class_key' => 'warrior', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '⚔', 'description' => 'A heavier steel blade, well beyond a common forge job.', 'stat_json' => ['atk' => 68], 'price_gold' => null, 'price_gems' => 300],
            ['key' => 'serrated_kris', 'name' => 'Serrated Kris', 'type' => 'weapon', 'weapon_category' => 'dagger', 'class_key' => 'rogue', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '🗡', 'description' => 'A wave-bladed dagger honed to bite deep and fast.', 'stat_json' => ['atk' => 64, 'crit' => 5], 'price_gold' => null, 'price_gems' => 300],
            ['key' => 'recurve_longbow', 'name' => 'Recurve Longbow', 'type' => 'weapon', 'weapon_category' => 'bow', 'class_key' => 'ranger', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '🏹', 'description' => 'A recurve bow with real reach and a clean release.', 'stat_json' => ['atk' => 66, 'dodge_pct' => 3], 'price_gold' => null, 'price_gems' => 300],
            ['key' => 'hunters_quiver', 'name' => "Hunter's Quiver", 'type' => 'quiver', 'weapon_category' => 'quiver', 'class_key' => 'ranger', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '🎯', 'description' => 'Broadhead arrows built to punch through hide.', 'stat_json' => ['atk' => 33, 'crit' => 3], 'price_gold' => null, 'price_gems' => 250],
            ['key' => 'ashwood_staff', 'name' => 'Ashwood Staff', 'type' => 'weapon', 'weapon_category' => 'staff', 'class_key' => 'mage', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '🔮', 'description' => 'An ashwood staff that holds a real mana reservoir.', 'stat_json' => ['atk' => 48, 'mp' => 35], 'price_gold' => null, 'price_gems' => 300],
            ['key' => 'steel_kite_shield', 'name' => 'Steel Kite Shield', 'type' => 'shield', 'class_key' => 'warrior', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '🛡', 'description' => 'A tall steel kite shield — bigger coverage than the starter buckler.', 'stat_json' => ['def' => 55], 'price_gold' => null, 'price_gems' => 300],
            ['key' => 'banded_cuirass', 'name' => 'Banded Cuirass', 'type' => 'armor', 'class_key' => 'warrior', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '🥋', 'description' => 'Overlapping steel bands over leather — solid, unglamorous chest protection.', 'stat_json' => ['def' => 26], 'price_gold' => null, 'price_gems' => 300],
            ['key' => 'shadowweave_jerkin', 'name' => 'Shadowweave Jerkin', 'type' => 'armor', 'class_key' => 'rogue', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '🥋', 'description' => 'A tightly woven jerkin, dark and unobtrusive.', 'stat_json' => ['def' => 38, 'crit' => 5], 'price_gold' => null, 'price_gems' => 300],
            ['key' => 'fletchers_cloak', 'name' => "Fletcher's Cloak", 'type' => 'armor', 'class_key' => 'ranger', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '🧥', 'description' => 'A cloak cut for quick, silent footwork.', 'stat_json' => ['def' => 40, 'dodge_pct' => 10], 'price_gold' => null, 'price_gems' => 300],
            ['key' => 'woven_mana_robe', 'name' => 'Woven Mana Robe', 'type' => 'armor', 'class_key' => 'mage', 'rarity' => 'rare', 'min_level' => 15, 'glyph' => '👘', 'description' => 'A robe woven with mana-conductive thread.', 'stat_json' => ['def' => 36, 'mp' => 45], 'price_gold' => null, 'price_gems' => 300],

            // Epic tier (level 20) — the old universal Silvered Blade is now the warrior's epic sword only;
            // the other three classes get their own silvered-tier weapon, and every class gets a matching shield/armor.
            ['key' => 'silvered_blade', 'name' => 'Silvered Broadsword', 'type' => 'weapon', 'weapon_category' => 'sword', 'class_key' => 'warrior', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '⚔', 'description' => 'A blade tempered with silver — a real test of your Crafting rank.', 'stat_json' => ['atk' => 110, 'crit' => 4], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'silvered_fang', 'name' => 'Silvered Fang', 'type' => 'weapon', 'weapon_category' => 'dagger', 'class_key' => 'rogue', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '🗡', 'description' => 'A silver-inlaid fang of a blade, built for a killing crit.', 'stat_json' => ['atk' => 105, 'crit' => 10], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'silvered_recurve', 'name' => 'Silvered Recurve', 'type' => 'weapon', 'weapon_category' => 'bow', 'class_key' => 'ranger', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '🏹', 'description' => 'A silver-limbed recurve bow with a hair-trigger release.', 'stat_json' => ['atk' => 108, 'dodge_pct' => 5], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'silvered_quiver', 'name' => 'Silvered Quiver', 'type' => 'quiver', 'weapon_category' => 'quiver', 'class_key' => 'ranger', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '🎯', 'description' => 'Silver-tipped arrows, a real test of your Crafting rank.', 'stat_json' => ['atk' => 54, 'crit' => 5], 'price_gold' => null, 'price_gems' => 500],
            ['key' => 'silvertide_staff', 'name' => 'Silvertide Staff', 'type' => 'weapon', 'weapon_category' => 'staff', 'class_key' => 'mage', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '🔮', 'description' => 'A silver-veined staff that swells with mana like a tide.', 'stat_json' => ['atk' => 80, 'mp' => 60], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'silverguard_aegis', 'name' => 'Silverguard Aegis', 'type' => 'shield', 'class_key' => 'warrior', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '🛡', 'description' => 'A silvered aegis shield — a real test of your Crafting rank.', 'stat_json' => ['def' => 95], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'silverplate_harness', 'name' => 'Silverplate Harness', 'type' => 'armor', 'class_key' => 'warrior', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '🥋', 'description' => 'A silver-reinforced harness worn under the shield arm.', 'stat_json' => ['def' => 45], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'nightsilver_leathers', 'name' => 'Nightsilver Leathers', 'type' => 'armor', 'class_key' => 'rogue', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '🥋', 'description' => 'Silver-threaded leathers that move like a shadow.', 'stat_json' => ['def' => 65, 'crit' => 8], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'silverleaf_cloak', 'name' => 'Silverleaf Cloak', 'type' => 'armor', 'class_key' => 'ranger', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '🧥', 'description' => 'A cloak lined with silver leaf, light as air.', 'stat_json' => ['def' => 68, 'dodge_pct' => 12], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'silverweave_robe', 'name' => 'Silverweave_robe', 'type' => 'armor', 'class_key' => 'mage', 'rarity' => 'epic', 'min_level' => 20, 'glyph' => '👘', 'description' => 'A robe woven from silver-spun thread, thick with stored mana.', 'stat_json' => ['def' => 62, 'mp' => 70], 'price_gold' => null, 'price_gems' => 600],

            // Legendary tier (level 35) — the old universal Gilded Saber is now the warrior's legendary sword only.
            ['key' => 'gilded_saber', 'name' => 'Gilded Broadsword', 'type' => 'weapon', 'weapon_category' => 'sword', 'class_key' => 'warrior', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '⚔', 'description' => 'A saber cast in gold and bound in elderwood — a serious material investment.', 'stat_json' => ['atk' => 150, 'crit' => 8], 'price_gold' => null, 'price_gems' => 2500],
            ['key' => 'gilded_fang', 'name' => 'Gilded Fang', 'type' => 'weapon', 'weapon_category' => 'dagger', 'class_key' => 'rogue', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '🗡', 'description' => 'A gold-cast fang blade that draws blood in an instant.', 'stat_json' => ['atk' => 145, 'crit' => 16], 'price_gold' => null, 'price_gems' => 2500],
            ['key' => 'gilded_war_bow', 'name' => 'Gilded War Bow', 'type' => 'weapon', 'weapon_category' => 'bow', 'class_key' => 'ranger', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '🏹', 'description' => 'A gold-limbed war bow that puts an arrow through anything.', 'stat_json' => ['atk' => 148, 'dodge_pct' => 8], 'price_gold' => null, 'price_gems' => 2500],
            ['key' => 'gilded_quiver', 'name' => 'Gilded Quiver', 'type' => 'quiver', 'weapon_category' => 'quiver', 'class_key' => 'ranger', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '🎯', 'description' => 'Gold-banded arrows, fletched with elderwood — a serious material investment.', 'stat_json' => ['atk' => 74, 'crit' => 8], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'gilded_spire_staff', 'name' => 'Gilded Spire Staff', 'type' => 'weapon', 'weapon_category' => 'staff', 'class_key' => 'mage', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '🔮', 'description' => 'A gold-capped spire staff brimming with stored mana.', 'stat_json' => ['atk' => 115, 'mp' => 90], 'price_gold' => null, 'price_gems' => 2500],
            ['key' => 'guardians_bulwark', 'name' => "Guardian's Bulwark", 'type' => 'shield', 'class_key' => 'warrior', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '🛡', 'description' => 'A massive gold-bound bulwark shield blessed by the old gods.', 'stat_json' => ['def' => 150], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'duskblade_leathers', 'name' => 'Duskblade Leathers', 'type' => 'armor', 'class_key' => 'rogue', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '🥋', 'description' => 'Gold-threaded leathers that seem to drink the light.', 'stat_json' => ['def' => 95, 'crit' => 14], 'price_gold' => null, 'price_gems' => 2500],
            ['key' => 'stormwatch_cloak', 'name' => 'Stormwatch Cloak', 'type' => 'armor', 'class_key' => 'ranger', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '🧥', 'description' => 'A storm-touched cloak that seems to bend arrows around you.', 'stat_json' => ['def' => 98, 'dodge_pct' => 16], 'price_gold' => null, 'price_gems' => 2500],
            ['key' => 'gilded_aether_robe', 'name' => 'Gilded Aether Robe', 'type' => 'armor', 'class_key' => 'mage', 'rarity' => 'legendary', 'min_level' => 35, 'glyph' => '👘', 'description' => 'A gold-hemmed robe that hums with raw aether.', 'stat_json' => ['def' => 92, 'mp' => 100], 'price_gold' => null, 'price_gems' => 2500],

            // Mythic tier (level 50) — the old universal Mythril Aegis is now the warrior's mythic shield only.
            ['key' => 'mythril_greatblade', 'name' => 'Mythril Greatblade', 'type' => 'weapon', 'weapon_category' => 'sword', 'class_key' => 'warrior', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '⚔', 'description' => 'A mythril greatblade — the pinnacle of the forge, weapon half of the set.', 'stat_json' => ['atk' => 205, 'crit' => 10], 'price_gold' => null, 'price_gems' => 5000],
            ['key' => 'mythril_fang', 'name' => 'Mythril Fang', 'type' => 'weapon', 'weapon_category' => 'dagger', 'class_key' => 'rogue', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '🗡', 'description' => 'A mythril fang blade honed to a near-mythical edge.', 'stat_json' => ['atk' => 198, 'crit' => 22], 'price_gold' => null, 'price_gems' => 5000],
            ['key' => 'mythril_war_bow', 'name' => 'Mythril War Bow', 'type' => 'weapon', 'weapon_category' => 'bow', 'class_key' => 'ranger', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '🏹', 'description' => 'A mythril war bow strung with moonwood-cored sinew.', 'stat_json' => ['atk' => 200, 'dodge_pct' => 12], 'price_gold' => null, 'price_gems' => 5000],
            ['key' => 'mythril_quiver', 'name' => 'Mythril Quiver', 'type' => 'quiver', 'weapon_category' => 'quiver', 'class_key' => 'ranger', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '🎯', 'description' => 'Mythril-tipped arrows, near-mythical in their killing power — the pinnacle of the fletcher\'s craft.', 'stat_json' => ['atk' => 100, 'crit' => 12], 'price_gold' => null, 'price_gems' => 4000],
            ['key' => 'mythril_spire_staff', 'name' => 'Mythril Spire Staff', 'type' => 'weapon', 'weapon_category' => 'staff', 'class_key' => 'mage', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '🔮', 'description' => 'A mythril-capped spire staff, a near-mythical mana conduit.', 'stat_json' => ['atk' => 155, 'mp' => 130], 'price_gold' => null, 'price_gems' => 5000],
            ['key' => 'mythril_aegis', 'name' => 'Titanguard Aegis', 'type' => 'shield', 'class_key' => 'warrior', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '🛡', 'description' => 'A ward-etched aegis shield of mythril and moonwood — the pinnacle of the forge, shield half of the set.', 'stat_json' => ['def' => 220], 'price_gold' => null, 'price_gems' => 5000],
            ['key' => 'titanplate_cuirass', 'name' => 'Titanplate Cuirass', 'type' => 'armor', 'class_key' => 'warrior', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '🥋', 'description' => 'A mythril-plated cuirass etched with the same wards as its shield — chest half of the set.', 'stat_json' => ['def' => 95], 'price_gold' => null, 'price_gems' => 5000],
            ['key' => 'voidsilk_leathers', 'name' => 'Voidsilk Leathers', 'type' => 'armor', 'class_key' => 'rogue', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '🥋', 'description' => 'Leathers spun from near-mythical voidsilk.', 'stat_json' => ['def' => 140, 'crit' => 18], 'price_gold' => null, 'price_gems' => 5000],
            ['key' => 'wraithwind_cloak', 'name' => 'Wraithwind Cloak', 'type' => 'armor', 'class_key' => 'ranger', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '🧥', 'description' => 'A cloak that moves like wraith-wind, near-impossible to pin down.', 'stat_json' => ['def' => 145, 'dodge_pct' => 20], 'price_gold' => null, 'price_gems' => 5000],
            ['key' => 'mythril_aether_robe', 'name' => 'Mythril Aether Robe', 'type' => 'armor', 'class_key' => 'mage', 'rarity' => 'mythic', 'min_level' => 50, 'glyph' => '👘', 'description' => 'A robe woven from mythril thread, a near-mythical aether well.', 'stat_json' => ['def' => 135, 'mp' => 150], 'price_gold' => null, 'price_gems' => 5000],

            // Tools — equip one to boost that gathering skill's speed and yield. Higher tiers need rarer ore/wood to forge.
            ['key' => 'stone_pickaxe', 'name' => 'Stone Pickaxe', 'type' => 'pickaxe', 'rarity' => 'common', 'glyph' => '⛏', 'description' => 'A crude pickaxe. Speeds up Mining a little.', 'stat_json' => ['gather_speed_pct' => 5, 'gather_yield_bonus' => 0], 'price_gold' => 1000, 'price_gems' => null],
            ['key' => 'iron_pickaxe', 'name' => 'Iron Pickaxe', 'type' => 'pickaxe', 'rarity' => 'rare', 'glyph' => '⛏', 'description' => 'A well-forged pickaxe. Speeds up Mining and finds a bit more ore per swing.', 'stat_json' => ['gather_speed_pct' => 10, 'gather_yield_bonus' => 1], 'price_gold' => 1000, 'price_gems' => null],
            ['key' => 'silver_pickaxe', 'name' => 'Silver Pickaxe', 'type' => 'pickaxe', 'rarity' => 'epic', 'glyph' => '⛏', 'description' => 'A gleaming pickaxe with a keen edge.', 'stat_json' => ['gather_speed_pct' => 15, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => 500],
            ['key' => 'gold_pickaxe', 'name' => 'Gold Pickaxe', 'type' => 'pickaxe', 'rarity' => 'legendary', 'glyph' => '⛏', 'description' => 'A dense, expensive pickaxe that tears through rock.', 'stat_json' => ['gather_speed_pct' => 20, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'mythril_pickaxe', 'name' => 'Mythril Pickaxe', 'type' => 'pickaxe', 'rarity' => 'mythic', 'glyph' => '⛏', 'description' => 'The finest pickaxe money can buy — at a price only a seasoned miner could justify.', 'stat_json' => ['gather_speed_pct' => 25, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => 4500],
            ['key' => 'wood_axe', 'name' => 'Wood Axe', 'type' => 'axe', 'rarity' => 'common', 'glyph' => '🪓', 'description' => 'A crude axe. Speeds up Woodchopping a little.', 'stat_json' => ['gather_speed_pct' => 5, 'gather_yield_bonus' => 0], 'price_gold' => 1000, 'price_gems' => null],
            ['key' => 'oak_axe', 'name' => 'Oak Axe', 'type' => 'axe', 'rarity' => 'rare', 'glyph' => '🪓', 'description' => 'A sturdier axe. Speeds up Woodchopping and yields a bit more timber per swing.', 'stat_json' => ['gather_speed_pct' => 10, 'gather_yield_bonus' => 1], 'price_gold' => 1000, 'price_gems' => null],
            ['key' => 'ironwood_axe', 'name' => 'Ironwood Axe', 'type' => 'axe', 'rarity' => 'epic', 'glyph' => '🪓', 'description' => 'An axe with an iron-hard head that bites deep.', 'stat_json' => ['gather_speed_pct' => 15, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => 500],
            ['key' => 'elderwood_axe', 'name' => 'Elderwood Axe', 'type' => 'axe', 'rarity' => 'legendary', 'glyph' => '🪓', 'description' => 'A heavy, expensive axe that fells trees in one stroke.', 'stat_json' => ['gather_speed_pct' => 20, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'moonwood_axe', 'name' => 'Moonwood Axe', 'type' => 'axe', 'rarity' => 'mythic', 'glyph' => '🪓', 'description' => 'The finest axe money can buy — at a price only a seasoned lumberjack could justify.', 'stat_json' => ['gather_speed_pct' => 25, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => 4500],
            ['key' => 'stone_sickle', 'name' => 'Stone Sickle', 'type' => 'sickle', 'rarity' => 'common', 'glyph' => '🔪', 'description' => 'A crude sickle. Speeds up Foraging a little.', 'stat_json' => ['gather_speed_pct' => 5, 'gather_yield_bonus' => 0], 'price_gold' => 1000, 'price_gems' => null],
            ['key' => 'iron_sickle', 'name' => 'Iron Sickle', 'type' => 'sickle', 'rarity' => 'rare', 'glyph' => '🔪', 'description' => 'A well-forged sickle. Speeds up Foraging and finds a bit more per cut.', 'stat_json' => ['gather_speed_pct' => 10, 'gather_yield_bonus' => 1], 'price_gold' => 1000, 'price_gems' => null],
            ['key' => 'silver_sickle', 'name' => 'Silver Sickle', 'type' => 'sickle', 'rarity' => 'epic', 'glyph' => '🔪', 'description' => 'A gleaming sickle with a keen edge.', 'stat_json' => ['gather_speed_pct' => 15, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => 500],
            ['key' => 'gold_sickle', 'name' => 'Gold Sickle', 'type' => 'sickle', 'rarity' => 'legendary', 'glyph' => '🔪', 'description' => 'A dense, expensive sickle that harvests with ease.', 'stat_json' => ['gather_speed_pct' => 20, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'mythril_sickle', 'name' => 'Mythril Sickle', 'type' => 'sickle', 'rarity' => 'mythic', 'glyph' => '🔪', 'description' => 'The finest sickle money can buy — at a price only a seasoned forager could justify.', 'stat_json' => ['gather_speed_pct' => 25, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => 4500],
            ['key' => 'wood_hammer', 'name' => 'Wood Hammer', 'type' => 'hammer', 'rarity' => 'common', 'glyph' => '🔨', 'description' => 'A crude hammer. Speeds up Crafting a little.', 'stat_json' => ['craft_speed_pct' => 5], 'price_gold' => 1000, 'price_gems' => null],
            ['key' => 'iron_hammer', 'name' => 'Iron Hammer', 'type' => 'hammer', 'rarity' => 'rare', 'glyph' => '🔨', 'description' => 'A well-balanced hammer. Speeds up Crafting further.', 'stat_json' => ['craft_speed_pct' => 10], 'price_gold' => 1000, 'price_gems' => null],
            ['key' => 'silver_hammer', 'name' => 'Silver Hammer', 'type' => 'hammer', 'rarity' => 'epic', 'glyph' => '🔨', 'description' => 'A precisely weighted hammer for faster forge-work.', 'stat_json' => ['craft_speed_pct' => 15], 'price_gold' => null, 'price_gems' => 500],
            ['key' => 'gold_hammer', 'name' => 'Gold Hammer', 'type' => 'hammer', 'rarity' => 'legendary', 'glyph' => '🔨', 'description' => 'A dense, expensive hammer that speeds through even complex crafts.', 'stat_json' => ['craft_speed_pct' => 20], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'mythril_hammer', 'name' => 'Mythril Hammer', 'type' => 'hammer', 'rarity' => 'mythic', 'glyph' => '🔨', 'description' => 'The finest hammer money can buy — at a price only a seasoned blacksmith could justify.', 'stat_json' => ['craft_speed_pct' => 25], 'price_gold' => null, 'price_gems' => 4500],

            // Repair packs — restore gear durability. Higher grade = more restored and a better chance to succeed;
            // using a pack below the item's grade still works, just with reduced odds and effect.
            ['key' => 'common_repair_pack', 'name' => 'Common Repair Pack', 'type' => 'repair_pack', 'rarity' => 'common', 'glyph' => '🧰', 'description' => 'Restores ~20% durability on same-grade gear, 70% chance to succeed.', 'stat_json' => [], 'price_gold' => 40, 'price_gems' => null],
            ['key' => 'rare_repair_pack', 'name' => 'Rare Repair Pack', 'type' => 'repair_pack', 'rarity' => 'rare', 'glyph' => '🧰', 'description' => 'Restores ~35% durability on same-grade gear, 78% chance to succeed.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 250],
            ['key' => 'epic_repair_pack', 'name' => 'Epic Repair Pack', 'type' => 'repair_pack', 'rarity' => 'epic', 'glyph' => '🧰', 'description' => 'Restores ~55% durability on same-grade gear, 85% chance to succeed.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 500],
            ['key' => 'legendary_repair_pack', 'name' => 'Legendary Repair Pack', 'type' => 'repair_pack', 'rarity' => 'legendary', 'glyph' => '🧰', 'description' => 'Restores ~75% durability on same-grade gear, 92% chance to succeed.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 2000],
            ['key' => 'mythic_repair_pack', 'name' => 'Mythic Repair Pack', 'type' => 'repair_pack', 'rarity' => 'mythic', 'glyph' => '🧰', 'description' => 'Fully restores durability on same-grade gear, 98% chance to succeed.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 4000],

            // Herbs — Foraging's gathered materials, the raw stock behind every craftable potion.
            ['key' => 'herb', 'name' => 'Herb', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🌿', 'description' => 'A common wayside herb. Rank up Foraging to find rarer blooms.', 'stat_json' => [], 'price_gold' => 5, 'price_gems' => null],
            ['key' => 'sage_leaf', 'name' => 'Sage Leaf', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🍃', 'description' => 'A fragrant, potent leaf — unlocked at Foraging level 8.', 'stat_json' => [], 'price_gold' => 18, 'price_gems' => null],
            ['key' => 'moonpetal', 'name' => 'Moonpetal', 'type' => 'material', 'rarity' => 'epic', 'glyph' => '🌸', 'description' => 'A pale bloom that only opens at night — unlocked at Foraging level 20.', 'stat_json' => [], 'price_gold' => 30, 'price_gems' => null],
            ['key' => 'sunroot', 'name' => 'Sunroot', 'type' => 'material', 'rarity' => 'legendary', 'glyph' => '🌻', 'description' => 'A root that stores warmth like embers — unlocked at Foraging level 35.', 'stat_json' => [], 'price_gold' => 120, 'price_gems' => null],
            ['key' => 'phoenix_bloom', 'name' => 'Phoenix Bloom', 'type' => 'material', 'rarity' => 'mythic', 'glyph' => '🔥', 'description' => 'A near-mythical flower said to bloom from embers — unlocked at Foraging level 50.', 'stat_json' => [], 'price_gold' => 300, 'price_gems' => null],

            // Craftable potions — brewed from foraged herbs, now also purchasable in shop. One HP-heal ("Poultice"),
            // one MP-heal ("Draught"), and one dual-regen buff ("Tonic") per herb tier, so every foraging
            // rank has a full potion line instead of just the HP one — the top mythic tier keeps its
            // signature Elixir (full heal + ATK buff) alongside its own Draught/Tonic.
            ['key' => 'herbal_poultice', 'name' => 'Herbal Poultice', 'type' => 'consumable', 'rarity' => 'common', 'glyph' => '🧴', 'description' => 'A simple herbal brew. Restores 35% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 35], 'price_gold' => 45, 'price_gems' => null],
            ['key' => 'herbal_draught', 'name' => 'Herbal Draught', 'type' => 'consumable', 'rarity' => 'common', 'glyph' => '🧪', 'description' => 'A simple herbal brew. Restores 35% of your max MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 35], 'price_gold' => 45, 'price_gems' => null],
            ['key' => 'sage_poultice', 'name' => 'Sage Poultice', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🧴', 'description' => 'A sage-infused brew. Restores 55% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 55], 'price_gold' => 160, 'price_gems' => null],
            ['key' => 'sage_draught', 'name' => 'Sage Draught', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🧪', 'description' => 'A sage-infused brew. Restores 55% of your max MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 55], 'price_gold' => 160, 'price_gems' => null],
            ['key' => 'sage_tonic', 'name' => 'Sage Tonic', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🍵', 'description' => '+45% HP and mana regen rate for 10 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 45, 'mana_regen_pct_buff' => 45, 'duration_seconds' => 600], 'price_gold' => 200, 'price_gems' => null],
            ['key' => 'moonpetal_poultice', 'name' => 'Moonpetal Poultice', 'type' => 'consumable', 'rarity' => 'epic', 'glyph' => '🧴', 'description' => 'A moonpetal-infused brew. Restores 70% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 70], 'price_gold' => 250, 'price_gems' => 450],
            ['key' => 'moonpetal_draught', 'name' => 'Moonpetal Draught', 'type' => 'consumable', 'rarity' => 'epic', 'glyph' => '🧪', 'description' => 'A moonpetal-infused brew. Restores 70% of your max MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 70], 'price_gold' => 250, 'price_gems' => 450],
            ['key' => 'moonpetal_tonic', 'name' => 'Moonpetal Tonic', 'type' => 'consumable', 'rarity' => 'epic', 'glyph' => '🍵', 'description' => '+60% HP and mana regen rate for 15 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 60, 'mana_regen_pct_buff' => 60, 'duration_seconds' => 900], 'price_gold' => 290, 'price_gems' => 550],
            ['key' => 'sunroot_poultice', 'name' => 'Sunroot Poultice', 'type' => 'consumable', 'rarity' => 'legendary', 'glyph' => '🧴', 'description' => 'A sunroot-infused brew. Restores 85% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 85], 'price_gold' => 450, 'price_gems' => 1800],
            ['key' => 'sunroot_draught', 'name' => 'Sunroot Draught', 'type' => 'consumable', 'rarity' => 'legendary', 'glyph' => '🧪', 'description' => 'A sunroot-infused brew. Restores 85% of your max MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 85], 'price_gold' => 450, 'price_gems' => 1800],
            ['key' => 'sunroot_tonic', 'name' => 'Sunroot Tonic', 'type' => 'consumable', 'rarity' => 'legendary', 'glyph' => '🍵', 'description' => '+75% HP and mana regen rate for 20 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 75, 'mana_regen_pct_buff' => 75, 'duration_seconds' => 1200], 'price_gold' => 500, 'price_gems' => 2200],
            ['key' => 'phoenix_elixir', 'name' => 'Phoenix Elixir', 'type' => 'consumable', 'rarity' => 'mythic', 'glyph' => '⚗', 'description' => 'Fully restores your HP and grants +30% ATK for your next two fights.', 'stat_json' => ['heal_hp_pct' => 100, 'atk_pct_buff' => 30, 'buff_fights' => 2], 'price_gold' => 850, 'price_gems' => 4500],
            ['key' => 'phoenix_draught', 'name' => 'Phoenix Draught', 'type' => 'consumable', 'rarity' => 'mythic', 'glyph' => '🧪', 'description' => 'Fully restores your MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 100], 'price_gold' => 850, 'price_gems' => 4200],
            ['key' => 'phoenix_tonic', 'name' => 'Phoenix Tonic', 'type' => 'consumable', 'rarity' => 'mythic', 'glyph' => '🍵', 'description' => '+90% HP and mana regen rate for 25 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 90, 'mana_regen_pct_buff' => 90, 'duration_seconds' => 1500], 'price_gold' => 900, 'price_gems' => 4800],
        ];

        foreach ($items as $item) {
            Item::updateOrCreate(['key' => $item['key']], $item);
        }
    }
}
