<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            ['key' => 'ashfang_blade', 'name' => 'Ashfang Blade', 'type' => 'weapon', 'class_key' => 'warrior', 'rarity' => 'legendary', 'glyph' => '⚔', 'description' => 'A blade forged in dragonfire. The signature legendary weapon of Season 3.', 'stat_json' => ['atk' => 180, 'crit' => 12], 'price_gold' => null, 'price_gems' => 500],
            ['key' => 'shadow_dagger', 'name' => 'Shadow Dagger', 'type' => 'weapon', 'class_key' => 'rogue', 'rarity' => 'epic', 'glyph' => '🗡', 'description' => 'A wickedly fast dagger that drains life on hit.', 'stat_json' => ['atk' => 120, 'lifesteal_pct' => 15], 'price_gold' => 900, 'price_gems' => null],
            ['key' => 'emberbow', 'name' => 'Emberbow', 'type' => 'weapon', 'class_key' => 'ranger', 'rarity' => 'rare', 'glyph' => '🏹', 'description' => 'A longbow strung with molten sinew for precise ranged damage.', 'stat_json' => ['atk' => 95], 'price_gold' => 400, 'price_gems' => null],
            ['key' => 'void_staff', 'name' => 'Void Staff', 'type' => 'weapon', 'class_key' => 'mage', 'rarity' => 'epic', 'glyph' => '🔮', 'description' => 'Channels raw void energy into devastating spells.', 'stat_json' => ['atk' => 140], 'price_gold' => 700, 'price_gems' => null],
            ['key' => 'aegis_plate', 'name' => 'Aegis Plate', 'type' => 'armor', 'class_key' => 'warrior', 'rarity' => 'legendary', 'glyph' => '🛡', 'description' => 'Impenetrable plate armor blessed by the old gods.', 'stat_json' => ['def' => 150], 'price_gold' => null, 'price_gems' => 600],
            ['key' => 'shadow_robe', 'name' => 'Shadow Robe', 'type' => 'armor', 'class_key' => 'mage', 'rarity' => 'epic', 'glyph' => '🥋', 'description' => 'Woven from shadowsilk; favored by mages.', 'stat_json' => ['def' => 90, 'mp' => 40], 'price_gold' => 800, 'price_gems' => null],
            ['key' => 'swift_boots', 'name' => 'Swift Boots', 'type' => 'armor', 'class_key' => 'rogue', 'rarity' => 'rare', 'glyph' => '👢', 'description' => 'Enchanted boots that make you harder to hit.', 'stat_json' => ['dodge_pct' => 15], 'price_gold' => 350, 'price_gems' => null],
            ['key' => 'health_potion', 'name' => 'Health Potion', 'type' => 'consumable', 'rarity' => 'common', 'glyph' => '🧪', 'description' => 'Restores 40% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 40], 'price_gold' => 50, 'price_gems' => null],
            ['key' => 'greater_health_potion', 'name' => 'Greater Health Potion', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🧪', 'description' => 'Restores 70% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 70], 'price_gold' => 180, 'price_gems' => null],
            ['key' => 'mana_potion', 'name' => 'Mana Potion', 'type' => 'consumable', 'rarity' => 'common', 'glyph' => '💧', 'description' => 'Restores 40% of your max MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 40], 'price_gold' => 50, 'price_gems' => null],
            ['key' => 'greater_mana_potion', 'name' => 'Greater Mana Potion', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '💧', 'description' => 'Restores 70% of your max MP instantly in battle.', 'stat_json' => ['heal_mp_pct' => 70], 'price_gold' => 180, 'price_gems' => null],
            ['key' => 'vitality_tonic', 'name' => 'Vitality Tonic', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🌿', 'description' => '+50% HP regen rate for 10 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 50, 'duration_seconds' => 600], 'price_gold' => 220, 'price_gems' => null],
            ['key' => 'focus_tonic', 'name' => 'Focus Tonic', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🔷', 'description' => '+50% mana regen rate for 10 minutes. Usable anytime, even outside battle.', 'stat_json' => ['mana_regen_pct_buff' => 50, 'duration_seconds' => 600], 'price_gold' => 220, 'price_gems' => null],
            ['key' => 'elixir_of_vigor', 'name' => 'Elixir of Vigor', 'type' => 'consumable', 'rarity' => 'epic', 'glyph' => '✨', 'description' => '+40% HP and mana regen rate for 15 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 40, 'mana_regen_pct_buff' => 40, 'duration_seconds' => 900], 'price_gold' => null, 'price_gems' => 120],
            ['key' => 'elixir_of_power', 'name' => 'Elixir of Power', 'type' => 'consumable', 'rarity' => 'legendary', 'glyph' => '⚗', 'description' => 'Grants +50% ATK for your next three fights.', 'stat_json' => ['atk_pct_buff' => 50, 'buff_fights' => 3], 'price_gold' => null, 'price_gems' => 180],
            ['key' => 'golden_crown', 'name' => 'Golden Crown', 'type' => 'cosmetic', 'rarity' => 'legendary', 'glyph' => '👑', 'description' => 'A pure flex — no combat stats, all prestige.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 200],
            ['key' => 'stone', 'name' => 'Stone', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🪨', 'description' => 'Plain rock — all a fresh pickaxe turns up. Rank up Mining to start finding ore.', 'stat_json' => [], 'price_gold' => 5, 'price_gems' => null],
            ['key' => 'iron_ore', 'name' => 'Iron Ore', 'type' => 'material', 'rarity' => 'common', 'glyph' => '💎', 'description' => 'Basic mining material — unlocked at Mining level 8. Smelt it into bars before crafting.', 'stat_json' => [], 'price_gold' => 10, 'price_gems' => null],
            ['key' => 'silver_ore', 'name' => 'Silver Ore', 'type' => 'material', 'rarity' => 'epic', 'glyph' => '🔹', 'description' => 'A richer vein — unlocked at Mining level 20.', 'stat_json' => [], 'price_gold' => 30, 'price_gems' => null],
            ['key' => 'gold_ore', 'name' => 'Gold Ore', 'type' => 'material', 'rarity' => 'legendary', 'glyph' => '🟡', 'description' => 'A gleaming vein — unlocked at Mining level 35.', 'stat_json' => [], 'price_gold' => 120, 'price_gems' => null],
            ['key' => 'mythril_ore', 'name' => 'Mythril Ore', 'type' => 'material', 'rarity' => 'mythic', 'glyph' => '🔷', 'description' => 'A near-mythical vein — unlocked at Mining level 50.', 'stat_json' => [], 'price_gold' => 300, 'price_gems' => null],
            ['key' => 'wood', 'name' => 'Wood', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🪵', 'description' => 'Plain lumber — all a fresh axe turns up. Rank up Woodchopping to start finding rarer timber.', 'stat_json' => [], 'price_gold' => 8, 'price_gems' => null],
            ['key' => 'oak_wood', 'name' => 'Oak Wood', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🌳', 'description' => 'Sturdier timber — unlocked at Woodchopping level 8.', 'stat_json' => [], 'price_gold' => 18, 'price_gems' => null],
            ['key' => 'ironwood', 'name' => 'Ironwood', 'type' => 'material', 'rarity' => 'epic', 'glyph' => '🌲', 'description' => 'Dense, iron-hard timber — unlocked at Woodchopping level 20.', 'stat_json' => [], 'price_gold' => 28, 'price_gems' => null],
            ['key' => 'elderwood', 'name' => 'Elderwood', 'type' => 'material', 'rarity' => 'legendary', 'glyph' => '🍂', 'description' => 'Ancient, richly grained timber — unlocked at Woodchopping level 35.', 'stat_json' => [], 'price_gold' => 110, 'price_gems' => null],
            ['key' => 'moonwood', 'name' => 'Moonwood', 'type' => 'material', 'rarity' => 'mythic', 'glyph' => '🌙', 'description' => 'Pale, near-mythical timber — unlocked at Woodchopping level 50.', 'stat_json' => [], 'price_gold' => 280, 'price_gems' => null],
            ['key' => 'iron_bar', 'name' => 'Iron Bar', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🔩', 'description' => 'Iron ore smelted at the forge, ready for crafting.', 'stat_json' => [], 'price_gold' => 25, 'price_gems' => null],
            ['key' => 'silver_bar', 'name' => 'Silver Bar', 'type' => 'material', 'rarity' => 'epic', 'glyph' => '⬜', 'description' => 'Silver ore smelted at the forge — unlocked at Smelting level 15.', 'stat_json' => [], 'price_gold' => 65, 'price_gems' => null],
            ['key' => 'gold_bar', 'name' => 'Gold Bar', 'type' => 'material', 'rarity' => 'legendary', 'glyph' => '🥇', 'description' => 'Gold ore smelted at the forge — unlocked at Smelting level 30.', 'stat_json' => [], 'price_gold' => 200, 'price_gems' => null],
            ['key' => 'mythril_bar', 'name' => 'Mythril Bar', 'type' => 'material', 'rarity' => 'mythic', 'glyph' => '💠', 'description' => 'Mythril ore smelted at the forge — unlocked at Smelting level 45.', 'stat_json' => [], 'price_gold' => 480, 'price_gems' => null],
            // Common tier is class-specific from level 8 on — each class crafts its own weapon+armor line,
            // stats flavored to fit (mage leans mana, rogue leans crit/dodge, ranger leans dodge, warrior leans raw def).
            ['key' => 'stone_shiv', 'name' => 'Stone Shiv', 'type' => 'weapon', 'class_key' => null, 'rarity' => 'common', 'glyph' => '🔪', 'description' => 'A crude blade knapped from raw stone. Cheap, quick, available from day one — any class can wield it.', 'stat_json' => ['atk' => 20], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'iron_sword', 'name' => 'Iron Sword', 'type' => 'weapon', 'class_key' => 'warrior', 'rarity' => 'common', 'glyph' => '⚔', 'description' => 'A plain but reliable blade, forged for the front line.', 'stat_json' => ['atk' => 42], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'iron_dagger', 'name' => 'Iron Dagger', 'type' => 'weapon', 'class_key' => 'rogue', 'rarity' => 'common', 'glyph' => '🗡', 'description' => 'A basic dagger, forged from crafting materials rather than bought.', 'stat_json' => ['atk' => 40, 'crit' => 2], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'wooden_bow', 'name' => 'Wooden Bow', 'type' => 'weapon', 'class_key' => 'ranger', 'rarity' => 'common', 'glyph' => '🏹', 'description' => 'A simple bow carved from chopped wood.', 'stat_json' => ['atk' => 45], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'oak_staff', 'name' => 'Oak Staff', 'type' => 'weapon', 'class_key' => 'mage', 'rarity' => 'common', 'glyph' => '🔮', 'description' => 'A gnarled oak staff that channels a modest reserve of mana.', 'stat_json' => ['atk' => 30, 'mp' => 15], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'iron_buckler', 'name' => 'Iron Buckler', 'type' => 'armor', 'class_key' => 'warrior', 'rarity' => 'common', 'glyph' => '🛡', 'description' => 'A sturdy buckler forged from iron bars.', 'stat_json' => ['def' => 35], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'leather_vest', 'name' => 'Leather Vest', 'type' => 'armor', 'class_key' => 'rogue', 'rarity' => 'common', 'glyph' => '🥋', 'description' => 'Light, flexible armor that never slows a blade down.', 'stat_json' => ['def' => 22, 'crit' => 3], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'ranger_cloak', 'name' => "Ranger's Cloak", 'type' => 'armor', 'class_key' => 'ranger', 'rarity' => 'common', 'glyph' => '🧥', 'description' => 'A weathered cloak that helps you slip out of harm\'s way.', 'stat_json' => ['def' => 22, 'dodge_pct' => 8], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'padded_robe', 'name' => 'Padded Robe', 'type' => 'armor', 'class_key' => 'mage', 'rarity' => 'common', 'glyph' => '👘', 'description' => 'A quilted robe woven to hold a bit of extra mana.', 'stat_json' => ['def' => 20, 'mp' => 20], 'price_gold' => null, 'price_gems' => null],
            // Mid/high/mythic tiers stay universal for now — every class can craft up into these once they hit rank.
            ['key' => 'silvered_blade', 'name' => 'Silvered Blade', 'type' => 'weapon', 'class_key' => null, 'rarity' => 'epic', 'glyph' => '⚔', 'description' => 'A blade tempered with silver — a real test of your Crafting rank.', 'stat_json' => ['atk' => 110, 'crit' => 4], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'gilded_saber', 'name' => 'Gilded Saber', 'type' => 'weapon', 'class_key' => null, 'rarity' => 'legendary', 'glyph' => '⚔', 'description' => 'A saber cast in gold and bound in elderwood — a serious material investment.', 'stat_json' => ['atk' => 150, 'crit' => 8], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'mythril_aegis', 'name' => 'Mythril Aegis', 'type' => 'armor', 'class_key' => null, 'rarity' => 'mythic', 'glyph' => '🛡', 'description' => 'A ward-etched aegis of mythril and moonwood — the pinnacle of the forge.', 'stat_json' => ['def' => 220], 'price_gold' => null, 'price_gems' => null],

            // Tools — equip one to boost that gathering skill's speed and yield. Higher tiers need rarer ore/wood to forge.
            ['key' => 'stone_pickaxe', 'name' => 'Stone Pickaxe', 'type' => 'pickaxe', 'rarity' => 'common', 'glyph' => '⛏', 'description' => 'A crude pickaxe. Speeds up Mining a little.', 'stat_json' => ['gather_speed_pct' => 5, 'gather_yield_bonus' => 0], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'iron_pickaxe', 'name' => 'Iron Pickaxe', 'type' => 'pickaxe', 'rarity' => 'common', 'glyph' => '⛏', 'description' => 'A well-forged pickaxe. Speeds up Mining and finds a bit more ore per swing.', 'stat_json' => ['gather_speed_pct' => 10, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'silver_pickaxe', 'name' => 'Silver Pickaxe', 'type' => 'pickaxe', 'rarity' => 'epic', 'glyph' => '⛏', 'description' => 'A gleaming pickaxe with a keen edge.', 'stat_json' => ['gather_speed_pct' => 15, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'gold_pickaxe', 'name' => 'Gold Pickaxe', 'type' => 'pickaxe', 'rarity' => 'legendary', 'glyph' => '⛏', 'description' => 'A dense, expensive pickaxe that tears through rock.', 'stat_json' => ['gather_speed_pct' => 20, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'mythril_pickaxe', 'name' => 'Mythril Pickaxe', 'type' => 'pickaxe', 'rarity' => 'mythic', 'glyph' => '⛏', 'description' => 'The finest pickaxe money can\'t buy — only the forge can make one.', 'stat_json' => ['gather_speed_pct' => 25, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'wood_axe', 'name' => 'Wood Axe', 'type' => 'axe', 'rarity' => 'common', 'glyph' => '🪓', 'description' => 'A crude axe. Speeds up Woodchopping a little.', 'stat_json' => ['gather_speed_pct' => 5, 'gather_yield_bonus' => 0], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'oak_axe', 'name' => 'Oak Axe', 'type' => 'axe', 'rarity' => 'common', 'glyph' => '🪓', 'description' => 'A sturdier axe. Speeds up Woodchopping and yields a bit more timber per swing.', 'stat_json' => ['gather_speed_pct' => 10, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'ironwood_axe', 'name' => 'Ironwood Axe', 'type' => 'axe', 'rarity' => 'epic', 'glyph' => '🪓', 'description' => 'An axe with an iron-hard head that bites deep.', 'stat_json' => ['gather_speed_pct' => 15, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'elderwood_axe', 'name' => 'Elderwood Axe', 'type' => 'axe', 'rarity' => 'legendary', 'glyph' => '🪓', 'description' => 'A heavy, expensive axe that fells trees in one stroke.', 'stat_json' => ['gather_speed_pct' => 20, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'moonwood_axe', 'name' => 'Moonwood Axe', 'type' => 'axe', 'rarity' => 'mythic', 'glyph' => '🪓', 'description' => 'The finest axe money can\'t buy — only the forge can make one.', 'stat_json' => ['gather_speed_pct' => 25, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'stone_sickle', 'name' => 'Stone Sickle', 'type' => 'sickle', 'rarity' => 'common', 'glyph' => '🔪', 'description' => 'A crude sickle. Speeds up Foraging a little.', 'stat_json' => ['gather_speed_pct' => 5, 'gather_yield_bonus' => 0], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'iron_sickle', 'name' => 'Iron Sickle', 'type' => 'sickle', 'rarity' => 'common', 'glyph' => '🔪', 'description' => 'A well-forged sickle. Speeds up Foraging and finds a bit more per cut.', 'stat_json' => ['gather_speed_pct' => 10, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'silver_sickle', 'name' => 'Silver Sickle', 'type' => 'sickle', 'rarity' => 'epic', 'glyph' => '🔪', 'description' => 'A gleaming sickle with a keen edge.', 'stat_json' => ['gather_speed_pct' => 15, 'gather_yield_bonus' => 1], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'gold_sickle', 'name' => 'Gold Sickle', 'type' => 'sickle', 'rarity' => 'legendary', 'glyph' => '🔪', 'description' => 'A dense, expensive sickle that harvests with ease.', 'stat_json' => ['gather_speed_pct' => 20, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'mythril_sickle', 'name' => 'Mythril Sickle', 'type' => 'sickle', 'rarity' => 'mythic', 'glyph' => '🔪', 'description' => 'The finest sickle money can\'t buy — only the forge can make one.', 'stat_json' => ['gather_speed_pct' => 25, 'gather_yield_bonus' => 2], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'wood_hammer', 'name' => 'Wood Hammer', 'type' => 'hammer', 'rarity' => 'common', 'glyph' => '🔨', 'description' => 'A crude hammer. Speeds up Crafting a little.', 'stat_json' => ['craft_speed_pct' => 5], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'iron_hammer', 'name' => 'Iron Hammer', 'type' => 'hammer', 'rarity' => 'common', 'glyph' => '🔨', 'description' => 'A well-balanced hammer. Speeds up Crafting further.', 'stat_json' => ['craft_speed_pct' => 10], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'silver_hammer', 'name' => 'Silver Hammer', 'type' => 'hammer', 'rarity' => 'epic', 'glyph' => '🔨', 'description' => 'A precisely weighted hammer for faster forge-work.', 'stat_json' => ['craft_speed_pct' => 15], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'gold_hammer', 'name' => 'Gold Hammer', 'type' => 'hammer', 'rarity' => 'legendary', 'glyph' => '🔨', 'description' => 'A dense, expensive hammer that speeds through even complex crafts.', 'stat_json' => ['craft_speed_pct' => 20], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'mythril_hammer', 'name' => 'Mythril Hammer', 'type' => 'hammer', 'rarity' => 'mythic', 'glyph' => '🔨', 'description' => 'The finest hammer money can\'t buy — only the forge can make one.', 'stat_json' => ['craft_speed_pct' => 25], 'price_gold' => null, 'price_gems' => null],

            // Repair packs — restore gear durability. Higher grade = more restored and a better chance to succeed;
            // using a pack below the item's grade still works, just with reduced odds and effect.
            ['key' => 'common_repair_pack', 'name' => 'Common Repair Pack', 'type' => 'repair_pack', 'rarity' => 'common', 'glyph' => '🧰', 'description' => 'Restores ~20% durability on same-grade gear, 70% chance to succeed.', 'stat_json' => [], 'price_gold' => 40, 'price_gems' => null],
            ['key' => 'rare_repair_pack', 'name' => 'Rare Repair Pack', 'type' => 'repair_pack', 'rarity' => 'rare', 'glyph' => '🧰', 'description' => 'Restores ~35% durability on same-grade gear, 78% chance to succeed.', 'stat_json' => [], 'price_gold' => 100, 'price_gems' => null],
            ['key' => 'epic_repair_pack', 'name' => 'Epic Repair Pack', 'type' => 'repair_pack', 'rarity' => 'epic', 'glyph' => '🧰', 'description' => 'Restores ~55% durability on same-grade gear, 85% chance to succeed.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 60],
            ['key' => 'legendary_repair_pack', 'name' => 'Legendary Repair Pack', 'type' => 'repair_pack', 'rarity' => 'legendary', 'glyph' => '🧰', 'description' => 'Restores ~75% durability on same-grade gear, 92% chance to succeed.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 180],
            ['key' => 'mythic_repair_pack', 'name' => 'Mythic Repair Pack', 'type' => 'repair_pack', 'rarity' => 'mythic', 'glyph' => '🧰', 'description' => 'Fully restores durability on same-grade gear, 98% chance to succeed.', 'stat_json' => [], 'price_gold' => null, 'price_gems' => 260],

            // Herbs — Foraging's gathered materials, the raw stock behind every craftable potion.
            ['key' => 'herb', 'name' => 'Herb', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🌿', 'description' => 'A common wayside herb. Rank up Foraging to find rarer blooms.', 'stat_json' => [], 'price_gold' => 5, 'price_gems' => null],
            ['key' => 'sage_leaf', 'name' => 'Sage Leaf', 'type' => 'material', 'rarity' => 'common', 'glyph' => '🍃', 'description' => 'A fragrant, potent leaf — unlocked at Foraging level 8.', 'stat_json' => [], 'price_gold' => 18, 'price_gems' => null],
            ['key' => 'moonpetal', 'name' => 'Moonpetal', 'type' => 'material', 'rarity' => 'epic', 'glyph' => '🌸', 'description' => 'A pale bloom that only opens at night — unlocked at Foraging level 20.', 'stat_json' => [], 'price_gold' => 30, 'price_gems' => null],
            ['key' => 'sunroot', 'name' => 'Sunroot', 'type' => 'material', 'rarity' => 'legendary', 'glyph' => '🌻', 'description' => 'A root that stores warmth like embers — unlocked at Foraging level 35.', 'stat_json' => [], 'price_gold' => 120, 'price_gems' => null],
            ['key' => 'phoenix_bloom', 'name' => 'Phoenix Bloom', 'type' => 'material', 'rarity' => 'mythic', 'glyph' => '🔥', 'description' => 'A near-mythical flower said to bloom from embers — unlocked at Foraging level 50.', 'stat_json' => [], 'price_gold' => 300, 'price_gems' => null],

            // Craftable potions — brewed from foraged herbs rather than bought.
            ['key' => 'herbal_poultice', 'name' => 'Herbal Poultice', 'type' => 'consumable', 'rarity' => 'common', 'glyph' => '🧴', 'description' => 'A simple herbal brew. Restores 35% of your max HP instantly in battle.', 'stat_json' => ['heal_hp_pct' => 35], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'sage_tonic', 'name' => 'Sage Tonic', 'type' => 'consumable', 'rarity' => 'rare', 'glyph' => '🍵', 'description' => '+45% HP and mana regen rate for 10 minutes. Usable anytime, even outside battle.', 'stat_json' => ['hp_regen_pct_buff' => 45, 'mana_regen_pct_buff' => 45, 'duration_seconds' => 600], 'price_gold' => null, 'price_gems' => null],
            ['key' => 'phoenix_elixir', 'name' => 'Phoenix Elixir', 'type' => 'consumable', 'rarity' => 'mythic', 'glyph' => '⚗', 'description' => 'Fully restores your HP and grants +30% ATK for your next two fights.', 'stat_json' => ['heal_hp_pct' => 100, 'atk_pct_buff' => 30, 'buff_fights' => 2], 'price_gold' => null, 'price_gems' => null],
        ];

        foreach ($items as $item) {
            Item::updateOrCreate(['key' => $item['key']], $item);
        }
    }
}
