// Field schemas for the generic GM content editor — one entry per resource
// type the backend's GmContentController supports. `json` fields are edited
// as raw JSON text and parsed/stringified on load/save.
export const RESOURCE_SCHEMAS = {
  items: {
    label: 'Items',
    columns: ['id', 'key', 'name', 'type', 'rarity', 'enabled'],
    fields: [
      { name: 'key', type: 'text' },
      { name: 'name', type: 'text' },
      { name: 'type', type: 'select', options: ['weapon', 'armor', 'consumable', 'cosmetic', 'material'] },
      { name: 'rarity', type: 'select', options: ['common', 'rare', 'epic', 'legendary', 'mythic'] },
      { name: 'glyph', type: 'text' },
      { name: 'description', type: 'textarea' },
      { name: 'stat_json', type: 'json' },
      { name: 'price_gold', type: 'number' },
      { name: 'price_gems', type: 'number' },
      { name: 'enabled', type: 'checkbox' },
      { name: 'tester_only', type: 'checkbox' },
    ],
  },
  monsters: {
    label: 'Monsters',
    columns: ['id', 'key', 'name', 'hp', 'atk', 'min_level', 'enabled'],
    fields: [
      { name: 'key', type: 'text' },
      { name: 'name', type: 'text' },
      { name: 'glyph', type: 'text' },
      { name: 'hp', type: 'number' },
      { name: 'atk', type: 'number' },
      { name: 'gold', type: 'number' },
      { name: 'xp', type: 'number' },
      { name: 'gems', type: 'number' },
      { name: 'is_boss', type: 'checkbox' },
      { name: 'zone_id', type: 'number' },
      { name: 'min_level', type: 'number' },
      { name: 'loot_table_json', type: 'json' },
      { name: 'enabled', type: 'checkbox' },
      { name: 'tester_only', type: 'checkbox' },
    ],
  },
  zones: {
    label: 'Zones',
    columns: ['id', 'key', 'name', 'danger', 'min_level', 'locked', 'enabled'],
    fields: [
      { name: 'key', type: 'text' },
      { name: 'name', type: 'text' },
      { name: 'glyph', type: 'text' },
      { name: 'danger', type: 'select', options: ['safe', 'medium', 'high', 'deadly'] },
      { name: 'min_level', type: 'number' },
      { name: 'locked', type: 'checkbox' },
      { name: 'sort_order', type: 'number' },
      { name: 'enabled', type: 'checkbox' },
      { name: 'tester_only', type: 'checkbox' },
    ],
  },
  dungeons: {
    label: 'Dungeons',
    columns: ['id', 'key', 'name', 'difficulty', 'min_level', 'enabled'],
    fields: [
      { name: 'key', type: 'text' },
      { name: 'name', type: 'text' },
      { name: 'glyph', type: 'text' },
      { name: 'difficulty', type: 'select', options: ['normal', 'hard', 'raid', 'mythic'] },
      { name: 'boss_monster_id', type: 'number' },
      { name: 'min_level', type: 'number' },
      { name: 'party_size', type: 'number' },
      { name: 'drops_json', type: 'json' },
      { name: 'enabled', type: 'checkbox' },
      { name: 'tester_only', type: 'checkbox' },
    ],
  },
  quests: {
    label: 'Quests',
    columns: ['id', 'key', 'name', 'type', 'enabled'],
    fields: [
      { name: 'key', type: 'text' },
      { name: 'name', type: 'text' },
      { name: 'description', type: 'textarea' },
      { name: 'type', type: 'select', options: ['daily', 'weekly', 'main', 'raid'] },
      { name: 'goal_json', type: 'json' },
      { name: 'reward_json', type: 'json' },
      { name: 'enabled', type: 'checkbox' },
    ],
  },
  skills: {
    label: 'Skills',
    columns: ['id', 'key', 'name', 'branch', 'tier', 'level_req'],
    fields: [
      { name: 'branch', type: 'text' },
      { name: 'key', type: 'text' },
      { name: 'name', type: 'text' },
      { name: 'glyph', type: 'text' },
      { name: 'description', type: 'textarea' },
      { name: 'tier', type: 'number' },
      { name: 'level_req', type: 'number' },
      { name: 'mp_cost', type: 'number' },
      { name: 'effect_json', type: 'json' },
      { name: 'class_scope', type: 'text' },
    ],
  },
  recipes: {
    label: 'Recipes',
    columns: ['id', 'name', 'result_item_id', 'enabled'],
    fields: [
      { name: 'name', type: 'text' },
      { name: 'result_item_id', type: 'number' },
      { name: 'materials_json', type: 'json' },
      { name: 'enabled', type: 'checkbox' },
    ],
  },
  pets: {
    label: 'Companions',
    columns: ['id', 'key', 'name', 'unlock_gems', 'enabled'],
    fields: [
      { name: 'key', type: 'text' },
      { name: 'name', type: 'text' },
      { name: 'glyph', type: 'text' },
      { name: 'description', type: 'textarea' },
      { name: 'bonus_json', type: 'json' },
      { name: 'unlock_gems', type: 'number' },
      { name: 'enabled', type: 'checkbox' },
    ],
  },
  cosmetics: {
    label: 'Cosmetics',
    columns: ['id', 'key', 'type', 'name', 'rarity', 'cost_gems', 'enabled'],
    fields: [
      { name: 'key', type: 'text' },
      { name: 'type', type: 'select', options: ['title', 'color', 'banner', 'icon'] },
      { name: 'name', type: 'text' },
      { name: 'value', type: 'text' },
      { name: 'rarity', type: 'select', options: ['common', 'rare', 'epic', 'legendary', 'mythic'] },
      { name: 'category', type: 'select', options: ['leveling', 'mastery', 'raid', 'daily_weekly', 'event', 'purchased'] },
      { name: 'cost_gems', type: 'number' },
      { name: 'unlock_quest_key', type: 'text' },
      { name: 'unlock_event', type: 'text' },
      { name: 'enabled', type: 'checkbox' },
    ],
  },
  events: {
    label: 'Events',
    columns: ['id', 'name', 'type', 'active'],
    fields: [
      { name: 'name', type: 'text' },
      { name: 'type', type: 'select', options: ['bonus_xp', 'bonus_gold', 'world_boss', 'drop_up', 'login'] },
      { name: 'reward', type: 'text' },
      { name: 'effect_json', type: 'json' },
      { name: 'starts_at', type: 'text' },
      { name: 'ends_at', type: 'text' },
      { name: 'active', type: 'checkbox' },
    ],
  },
};
